episodes: 1000
total_timesteps: 50000
max_step: 500
buffer_size: 1000000
batch_size: 32
learning_rate: 0.0001
discount_rate: 0.99
state_size: 4
action_size: 2
target_update_steps: 1000
log_steps: 5000